workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Add iOS platform if missing
        script: |
          if [ ! -d ios/App ]; then
            echo "iOS platform missing – adding"
            npx cap add ios
          else
            echo "iOS platform exists"
          fi

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      - name: Build iOS archive (no signing)
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive

    artifacts:
      - build/App.xcarchive
