workflows:
  ios-capacitor:
    name: iOS Capacitor Build (No Signing)
    max_build_duration: 60

    environment:
      node: latest
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Sync Capacitor (create iOS project)
        script: |
          npx cap sync ios

      - name: Build iOS archive (xcodeproj, NO SIGNING)
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive

    artifacts:
      - build/App.xcarchive
