workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS archive (NO SIGNING)
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive

    artifacts:
      - build/App.xcarchive
